In [ ]:
import numpy as np

ASSIGNMENT NO 1

In [3]:
x = np.ones(50)

In [4]:
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
z = np.linspace(0,20,50)

In [4]:
z


array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [5]:
y = np.array([])

In [6]:
for no in np.linspace(0,20,50):
    y = np.append(y,no)

In [7]:
y


array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

finding the absolute difference between array (y) and array(x). Lets give it variable "differ"

In [9]:
differ = np.abs(np.subtract(y,z))

In [10]:
differ

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## ASSIGNMENT NO 2

(a)

In [57]:
mat = np.array([1])
mat.shape
np.random.randint(1,10)
np.append(mat, [23])


array([ 1, 23])

(b)

In [ ]:
while mat[-1] != 7:
    nrandom = np.random.randint(1,10) #get random number 
    np.append(mat,nrandom) #append random number
    
    print(nrandom)

ASSIGNMENT NO 3

In [4]:
a = np.array([ 8.,3.,10.,8.,2.,2.,10.,10.,5.,10.,2.,10.,9.,10.,9.,4.,2.,8.,7.,4.,1.,4.,5.,6.,6.])

In [5]:
a.shape = (5,5)

In [60]:
a

array([[ 8.,  3., 10.,  8.,  2.],
       [ 2., 10., 10.,  5., 10.],
       [ 2., 10.,  9., 10.,  9.],
       [ 4.,  2.,  8.,  7.,  4.],
       [ 1.,  4.,  5.,  6.,  6.]])

In [76]:

a

array([[ 8.,  3., 10.,  8.,  2.],
       [ 2., 10., 10.,  5., 10.],
       [ 2., 10.,  9., 10.,  9.],
       [ 4.,  2.,  8.,  7.,  4.],
       [ 1.,  4.,  5.,  6.,  6.]])

In [82]:
ind = 0
for iloop in np.nditer(a):
#     print(float(iloop))
    if float(iloop)== 5. or float(iloop) == 8.:
            print(ind)
    ind += 1
    
        
    

0
3
8
17
22
