In [1]:
2>4


False

In [2]:
34-32


2

In [3]:
np.arange()23


SyntaxError: invalid syntax (<ipython-input-3-5f797a851118>, line 1)

In [4]:
np.arange(23
         )

NameError: name 'np' is not defined

In [5]:
np.arange(21)

NameError: name 'np' is not defined

In [6]:
import numpy as np

In [8]:
arr = np.arange(23)

In [9]:
arr[5]

5

In [11]:
arrbool = arr > 4

In [15]:
arr[arrbool] = -1

In [16]:
arr


array([ 0,  1,  2,  3,  4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1])

In [18]:
a = np.array([[8,3,4],[4,5,3],[9,2,2]])

In [20]:
a[0]


array([8, 3, 4])

In [21]:
a[0:1]

array([[8, 3, 4]])

In [22]:
a[0:2]

array([[8, 3, 4],
       [4, 5, 3]])

In [23]:
a[0,2]

4

In [24]:
a[1,2]

3

In [25]:
a[2,0]

9

In [26]:
a

array([[8, 3, 4],
       [4, 5, 3],
       [9, 2, 2]])

In [27]:
a[0:3,0]

array([8, 4, 9])

In [28]:
a[0:3,1]

array([3, 5, 2])

In [29]:
a[0:3,2]

array([4, 3, 2])

In [30]:
a[:,0]

array([8, 4, 9])

In [31]:
a[:,0:2]

array([[8, 3],
       [4, 5],
       [9, 2]])

In [32]:
a[:,1:3]

array([[3, 4],
       [5, 3],
       [2, 2]])

In [33]:
a

array([[8, 3, 4],
       [4, 5, 3],
       [9, 2, 2]])

In [34]:
a[:,-1]

array([4, 3, 2])

In [35]:
b = np.array([[4,5,7,3],[2,6,5,4],[9,8,7,10],[2,4,3,1],[4,6,8,9]])

In [39]:
b[:,::-1]

array([[ 3,  7,  5,  4],
       [ 4,  5,  6,  2],
       [10,  7,  8,  9],
       [ 1,  3,  4,  2],
       [ 9,  8,  6,  4]])

In [41]:
np.zeros(4)


array([0., 0., 0., 0.])

In [42]:
b=np.zeros(6)

In [43]:
b


array([0., 0., 0., 0., 0., 0.])

In [49]:
b.shape = (6,1)

In [50]:
b


array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [51]:
b.shape = (3,2)

In [52]:
b


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
y = np.arange(10)

In [54]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
b = np.array([[8,3,4],[4,5,3],[9,2,2]])

In [56]:
b


array([[8, 3, 4],
       [4, 5, 3],
       [9, 2, 2]])

In [57]:
boolb = b>4

In [58]:
boolb

array([[ True, False, False],
       [False,  True, False],
       [ True, False, False]])

In [59]:
b[boolb]

array([8, 5, 9])

In [60]:
c = [8,3,5,6,8,]

In [61]:
c[2]

5

In [1]:
z = np.linspace(0,20,50)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
z = np.linspace(0,20,50)

In [4]:
z

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [11]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
np.arange(1,20,50)

array([1])

In [ ]:
a = []
for i in np.linspace(0,20,50):
           a.append(i)
  print(a)
        
          
    

In [1]:
y = np.array([])

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
y = np.array([])

In [17]:
for i in np.arange(0,20,2):
    y = np.append(y,i)

In [18]:
y

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.,  0.,  2.,  4.,  6.,  8., 10.,
       12., 14., 16., 18.,  0.,  2.,  4.,  6.,  8., 10., 12., 14., 16.,
       18.])

In [19]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
y= np.array([])

In [20]:
for i in np.arange(0,20,2):
    y = np.append(y,i)

In [21]:
y

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.,  0.,  2.,  4.,  6.,  8., 10.,
       12., 14., 16., 18.,  0.,  2.,  4.,  6.,  8., 10., 12., 14., 16.,
       18.,  0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [22]:
z = np.array([])


In [23]:
for i in np.linspace(0,20,50):
    z = np.append(z,i)

In [24]:
z

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [25]:
a = np.arange(10)

In [26]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
b = np.arange(3,13)

In [28]:
b

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
z = numpy.subtract

NameError: name 'numpy' is not defined

In [30]:
import numpy as np

In [31]:
z = np.subtract(b,a)

In [32]:
z

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [33]:
b-a

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [34]:
r = np.abs(np.subtract(b,a))

In [35]:
r

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [36]:
np.ones(4)

array([1., 1., 1., 1.])

In [40]:
np.random.normal(size=4)

array([ 0.18878467,  0.62433127, -0.32929689,  1.55678405])

In [41]:
np.random.randint(20,size=5)

array([ 3,  1,  5, 10, 11])

In [42]:
np.matrix("1 1  1 1 1 1 ")
    

matrix([[1, 1, 1, 1, 1, 1]])

In [44]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [45]:
np.matrix(np.array([2,3,4,5]))

matrix([[2, 3, 4, 5]])

In [48]:
x = np.random.randint(1,10, size=4)

In [49]:
x


array([7, 3, 2, 6])

In [52]:
x[-1]

6

In [ ]:
narray = np.array([])
while True:
    nrandom = np.random.randint(1,10)
    for x in np.nditer(nrandom):
        narray = np.append(narray,nrandom)
               
       

In [ ]:
narray

In [ ]:
a = np.array([ 8.,3.,10.,8.,2.,2.,10.,10.,5.,10.,2.,10.,9.,10.,9.,4.,2.,8.,7.,4.,1
.,4.,5.,6.,6.])
a  = np.reshape(5,5)

In [3]:
import numpy as np


In [4]:
a = np.array([ 8.,3.,10.,8.,2.,2.,10.,10.,5.,10.,2.,10.,9.,10.,9.,4.,2.,8.,7.,4.,1])


In [5]:
a

array([ 8.,  3., 10.,  8.,  2.,  2., 10., 10.,  5., 10.,  2., 10.,  9.,
       10.,  9.,  4.,  2.,  8.,  7.,  4.,  1.])

In [6]:
a.shape = (7,3)

In [7]:
a

array([[ 8.,  3., 10.],
       [ 8.,  2.,  2.],
       [10., 10.,  5.],
       [10.,  2., 10.],
       [ 9., 10.,  9.],
       [ 4.,  2.,  8.],
       [ 7.,  4.,  1.]])

In [ ]:
a np.array(3,4,5,6)

In [8]:
a

array([[ 8.,  3., 10.],
       [ 8.,  2.,  2.],
       [10., 10.,  5.],
       [10.,  2., 10.],
       [ 9., 10.,  9.],
       [ 4.,  2.,  8.],
       [ 7.,  4.,  1.]])

In [10]:
b = np.array([4,5,6,7])

In [11]:
b


array([4, 5, 6, 7])

In [12]:
b[2]

6

In [ ]:
np.